FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS builder
WORKDIR /app
COPY . .
RUN npm pkg delete scripts.preinstall && pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm --filter @workspace/api-server... run build

FROM base AS runner
WORKDIR /app
COPY --from=builder /app /app
CMD ["pnpm", "--filter", "@workspace/api-server", "run", "start"]
